config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :houses do
    resources :groups do
      resources :tasks
    end
  end

  root to: 'home#index'

  get 'users/:id', to: 'users#show', as: 'user'
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id/my_dashboard', to: 'users#dashboard', as: 'user_dashboard'
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show; end

  # GET /houses/new
  def new
    @house = House.new
    @house.HouseImage = params[:file]

    @house.HouseImage.url # => '/url/to/file.png'
    @house.HouseImage.thumb.url # => '/url/to/file.png' 200x200px
    @house.HouseImage.small_thumb.url # => '/url/to/file.png' 20x20px
    @house.HouseImage.current_path # => 'path/to/file.png'
    @house.HouseImage_identifier # => 'file.png'
  end

  # GET /houses/1/edit
  def edit
    authorize! :edit, @house, :message => "You are not authorized to edit this house. Sorry!"
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)
    @mate = Mate.new(user: current_user, house: @house, house_manager: true )

    respond_to do |format|
      if @house.save && @mate.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    if cannot? :destroy, @house
      respond_to do |format|
        format.html { redirect_to houses_url, notice: 'You are not authorized to delete the house.' }
        format.json { head :no_content }
      end
    else
      @house.destroy
      respond_to do |format|
        format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_house
    @house = House.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def house_params
    params.require(:house).permit(:name, :street, :number, :additionalinfo, :postalcode, :city, :about, :HouseImage)
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :house_name %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :house_street %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :house_number %>
  </div>

  <div class="field">
    <%= form.label :postalcode %>
    <%= form.number_field :postalcode, id: :house_postalcode %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :house_city %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about, id: :house_about %>
  </div>

  <div class="image">
    <%= form.label :image %><br>
    <%= image_tag(house.HouseImage.thumb.url) if house.HouseImage? %><br>
    <%= form.file_field :HouseImage, id: :house_HouseImage %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h2>Editing House</h2>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>House Manager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= link_to (image_tag house.HouseImage.small_thumb.url), house %></td>
        <td><%= link_to house.name, house %></td>
        <td><%= house.street %> <%= house.number %></td>
        <td><%= house.postalcode %> <%= house.city %></td>
        <td><%= house.house_manager.email%></td>
        <td><%= link_to 'Edit', edit_house_path(house) if can? :update, house %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-outline-secondary btn-sm">
  <%= link_to 'New House', new_house_path %>
</button>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @house.name %></h3>

<p>
  <strong>This is our house:</strong>
  <br>
  <%= image_tag @house.HouseImage.url%>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.street %>
  <%= @house.number %>
</p>

<p>
  <strong>City:</strong>
  <%= @house.postalcode %>
  <%= @house.city %>
</p>

<p>
  <strong>About:</strong>
  <%= @house.about %>
</p>

<p>
  <strong>House Manager:</strong>
  <%= @house.house_manager.email %>
</p>

<% if can? :update, @house %>
  <button type="button" class="btn btn-outline-secondary">
    <%= link_to 'Edit', edit_house_path(@house) %>
  </button>
<% end %>
<% if can? :destroy, @house %>
  <button type="button" class="btn btn-outline-secondary">
    <%= link_to 'Delete', house_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  </button>
<% end %>

<br>

<% if (can? :update, @house) && (can? :manage, Group) %> 
<!-- not the final solution as this will not work for house_mates (once defined) -->
<br>
<div>

  <h4>This house's groups:</h4>
  <%= link_to 'Show all', house_groups_path(@house) %>

  <% @house.groups.each do |group| %>
    <div>
      <strong>
      <%= link_to group.name, house_group_path(@house, group)  %>
      </strong>
    </div>
  <% end %>
</div>

<br>
<button type="button" class="btn btn-outline-secondary btn-sm">
  <%= link_to 'Create New Group', new_house_group_path(@house, @group) %>
</button>

<br>
<% end %>

<br>
<button type="button" class="btn btn-outline-secondary">
  <%= link_to 'Back to All Houses', houses_path %>
</button>
<button type="button" class="btn btn-outline-secondary">
  <%= link_to 'Back Home', root_path %>
</button>