config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :houses do
    resources :groups do
      resources :tasks
    end
  end

  root to: 'home#index'

  get 'users/:id', to: 'users#show', as: 'user'
  get 'users', to: 'users#index', as: 'users'
  get 'users/:id/my_dashboard', to: 'users#dashboard', as: 'user_dashboard'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Housemate</title>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Comfortaa|Lato','application.css' %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <h1><%= link_to "Housemate", root_path %></h1>

        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <%= link_to "New House", new_house_path %>
              </button>
            </li>
            <li>
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </button>
            </li>
            <li>
              Hi, 
              <% if current_user.nickname? %>
                <%= current_user.nickname %>
              <% else %>
                <%= current_user.email %>
              <% end %>
            </li>
            <li>
              <%= link_to "My Profile", user_path(current_user) %>
            </li>
            <li>
              <%= link_to 'My Dashboard', user_dashboard_path(current_user) %>
            </li>
          </ul>

        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <%= link_to "Sign Up", new_user_registration_path %>
              </button>
            </li>
            <li>
              <button type="button" class="btn btn-outline-secondary btn-sm">
                <%= link_to "Sign In", new_user_session_path %>
              </button>
            </li>
          </ul>
        <% end %>
      </div>
  </nav>

<br>

    <div class="container">
      <% if alert %>
        <p class="alert alert-danger alert-dismissible fade show"><%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </p>
      <% end %>
      <%= yield %>
    </div>
  
  </body>
</html>